<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionsSeeder extends Seeder
{
    /**
     * @var mixed|null
     */
    private $role;

    public function __invoke(array $parameters = [])
    {
        $this->role = isset($parameters[0])?$parameters[0] : null;
        return parent::__invoke($parameters); // TODO: Change the autogenerated stub
    }

    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $userRole = Role::updateOrCreate(['name' => $this->role, 'guard_name' => 'api']);
        foreach (User::$permissions[$this->role] as $permissionName) {
            $permission = Permission::updateOrCreate([
                'name' => $permissionName,
                'guard_name' => 'api'
            ]);

            $userRole->givePermissionTo($permission);
        }
    }
}
