<?php

namespace Database\Seeders;

use App\Models\Answer;
use App\Models\Question;
use App\Models\Survey;
use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class SurveySeeder extends Seeder
{
    /**
     * @var mixed|null
     */
    private $userId;

    public function __invoke(array $parameters = [])
    {
        $this->userId = isset($parameters[0]) ? $parameters[0] : null;
        return parent::__invoke($parameters); // TODO: Change the autogenerated stub
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if ($this->userId) {
            Survey::factory(5)->create([
                'user_id' => $this->userId
            ])->each(function ($survey) {
                $survey->questions()->saveMany(
                    Question::factory(10)->create()->each(function (Question $question) {
                        $question->answers()->saveMany(Answer::factory(5)->make());
                    })
                );
            });
        }
    }
}
